### ISSUE TITLE
Refactor code in OASIS

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#211]
Here records refactor suggestions for OASIS:

- [x] Change `ChargingStatus` -> `State` https://github.com/Telenav/osrm-backend/pull/204#discussion_r389808415
- [x] Change name of package `solutionformat` -> `solution` https://github.com/Telenav/osrm-backend/pull/205#discussion_r389678574
- [x] Replace `floatEquals` using the one defined in `util` https://github.com/Telenav/osrm-backend/pull/204#discussion_r389805704
- [x] Change interface name `ChargeStrategyCreator` to a shorter name https://github.com/Telenav/osrm-backend/issues/211#issuecomment-598297700
- [x] Move `location` to `integration/map` https://github.com/Telenav/osrm-backend/pull/204#discussion_r390419304
- [x] Refine the structure of `ChargeInfo` https://github.com/Telenav/osrm-backend/issues/211#issuecomment-597239787
- [ ] Change `ChargingCost`-> `Cost` https://github.com/Telenav/osrm-backend/pull/204#discussion_r389808415
- [x] Change from `cost` -> `weight` https://github.com/Telenav/osrm-backend/issues/201
- [ ] Refactor `State`, add member functions not expose internal state https://github.com/Telenav/osrm-backend/pull/224#discussion_r392787574

**Comment by CodeBear801** [comment]
https://github.com/Telenav/osrm-backend/pull/204#discussion_r389805704

**Comment by CodeBear801** [comment]
Suggestions:
https://github.com/Telenav/osrm-backend/pull/204#discussion_r390419304

**Comment by CodeBear801** [comment]
Suggestions for `chargeInfo`
Current definition is:
```
type chargeInfo struct {
	arrivalEnergy float64
	chargeTime    float64
	chargeEnergy  float64
}
```
- May be should change `chargeEnergy` to `chargestrategy->State`, use `State` to hide information of `chargeEnergy`, maybe later could add `cost`.
- `ChargeTime` could also be recorded in `State`, but I decide to still keep it in `chargeInfo`.  There might be a situation in the future, user only want to charge his car for certain time, such as 1 hour, he didn't care about how much energy could be charged.  So the final status of `state` still be fixed, just `charge duration` is pre-calculated by strategy but `chargeEnergy` is dynamic during evaluation.

**Comment by CodeBear801** [comment]
Suggestions:
https://github.com/Telenav/osrm-backend/pull/215#discussion_r391758613
