### ISSUE TITLE
Oasis - Extend oasis service's graph - multiple orig and destination

### ISSUE THREAD

**Issue by CodeBear801** [Telenav/osrm-backend#242]
Subtask of #231, more information go to #282 

update on 04302020
Original thinking is: before algorithm of `Dijkstra` starts, add all reachable charge stations from orig based on current energy into `Graph`, and for destination, add all charge station which is possible to charge there and reach destination.  Treat those points as origs and destinations for the algorithm

But I think we could hide those logic in the interface of `connectivityQuerier`
```
// Querier used to return topological information of charge stations
type Querier interface {
	// NearByStationQuery finds near by stations by given stationID and return them in recorded sequence
	// Returns nil if given stationID is not found or no connectivity
	NearByStationQuery(stationID string) []*QueryResult

	// GetLocation returns location of given station id
	// Returns nil if given stationID is not found
	GetLocation(stationID string) *nav.Location
}
```
- For the middle points, which is charge stations, it need to support get connectivity by calling `NearByStationQuery`
- For `orig` point, `Querier` need to support user query with a special string which represent for orig and returns all reachable charge stations, so information like `currentEnergyLevel` need to pass into implementation of `Querier`
- We also need special logic to connects `destination` into station graph

## Tasks
- [x]  implement station connectivity graph based on pre-build data https://github.com/Telenav/osrm-backend/issues/325
- [x] Record `duration` for pre-generated data https://github.com/Telenav/osrm-backend/issues/326
- [ ] refactor Oasis Ranker https://github.com/Telenav/osrm-backend/issues/321
- [x] add filter in `node_graph` to avoid visiting unreachable stations https://github.com/Telenav/osrm-backend/issues/338
- [ ] replace `Location` in spatialindexer to nav.Location, replace all name related with `point` to `place`
